name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Jasmine.Nova
          installers-regex: '\.exe$'
          release-tag: ${{ inputs.version }}
          max-versions-to-keep: 3
          token: ${{ secrets.WINGET_TOKEN }}