name: publish-to-winget
run-name: Publish to WinGet

on:
  workflow_dispatch:
    branches:
      - main
  release:
    types: [released]

env:
  WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.PUBLIC_ACCESS_TOKEN }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Jasmine.Nova
          installers-regex: 'nova-installer(64|32|)\.exe$'
          token: ${{ env.WINGET_TOKEN }}
