name: publish-to-winget
run-name: Publish to WinGet

on:
  workflow-dispatch:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Jasmine.Nova
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
